/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author leandro
 */
public class ConsultaAlbumPorArtista extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultaAlbumPorArtista
     */
    public ConsultaAlbumPorArtista() {
        initComponents();
        this.setSize(900,800);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaAlbumXArtPanel = new javax.swing.JPanel();
        LabelNombreArtista = new javax.swing.JLabel();
        nombreArtista = new javax.swing.JTextField();
        Buscarbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaAlbunesArtista = new javax.swing.JList<>();
        ConsultaAlbumButton = new javax.swing.JButton();
        SalirButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Consulta Album Por Artista");

        LabelNombreArtista.setText("Nombre del Artista");

        Buscarbutton.setText("Buscar ");

        jScrollPane1.setViewportView(ListaAlbunesArtista);

        ConsultaAlbumButton.setText("Consultar Album");

        SalirButton.setText("Salir");

        jLabel1.setText("Albums");

        javax.swing.GroupLayout ConsultaAlbumXArtPanelLayout = new javax.swing.GroupLayout(ConsultaAlbumXArtPanel);
        ConsultaAlbumXArtPanel.setLayout(ConsultaAlbumXArtPanelLayout);
        ConsultaAlbumXArtPanelLayout.setHorizontalGroup(
            ConsultaAlbumXArtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaAlbumXArtPanelLayout.createSequentialGroup()
                .addGroup(ConsultaAlbumXArtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConsultaAlbumXArtPanelLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(ConsultaAlbumXArtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConsultaAlbumXArtPanelLayout.createSequentialGroup()
                                .addComponent(LabelNombreArtista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ConsultaAlbumXArtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SalirButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ConsultaAlbumButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Buscarbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ConsultaAlbumXArtPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        ConsultaAlbumXArtPanelLayout.setVerticalGroup(
            ConsultaAlbumXArtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaAlbumXArtPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(ConsultaAlbumXArtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNombreArtista)
                    .addComponent(Buscarbutton))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaAlbumXArtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsultaAlbumXArtPanelLayout.createSequentialGroup()
                        .addComponent(ConsultaAlbumButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SalirButton)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsultaAlbumXArtPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ConsultaAlbumXArtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscarbutton;
    private javax.swing.JButton ConsultaAlbumButton;
    private javax.swing.JPanel ConsultaAlbumXArtPanel;
    private javax.swing.JLabel LabelNombreArtista;
    private javax.swing.JList<String> ListaAlbunesArtista;
    private javax.swing.JButton SalirButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreArtista;
    // End of variables declaration//GEN-END:variables
}
