/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author leandro
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setSize(1000, 600);
        this.setLocationRelativeTo(null);
        this.internalAltaPerfil.setSize(1422, 800);
        this.internalAltaPerfil.setVisible(false);
        this.setTitle("ESPOTIFY");
        this.internalAltaAlbum.setSize(1422, 800);
        this.internalAltaAlbum.setVisible(false);
        this.setTitle("ESPOTIFY");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalAltaAlbum = new javax.swing.JInternalFrame();
        internalAltaPerfil = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        SesionDropDown = new javax.swing.JMenu();
        cerrarOption = new javax.swing.JMenuItem();
        AltasDropDown = new javax.swing.JMenu();
        AltaPerfil = new javax.swing.JMenuItem();
        AltaAlbum = new javax.swing.JMenuItem();
        ConsultasDropDown = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 200, 700));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(3200, 1800));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        internalAltaAlbum.setBorder(null);
        internalAltaAlbum.setClosable(true);
        internalAltaAlbum.setTitle("Alta Album");
        internalAltaAlbum.setVisible(true);

        javax.swing.GroupLayout internalAltaAlbumLayout = new javax.swing.GroupLayout(internalAltaAlbum.getContentPane());
        internalAltaAlbum.getContentPane().setLayout(internalAltaAlbumLayout);
        internalAltaAlbumLayout.setHorizontalGroup(
            internalAltaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        internalAltaAlbumLayout.setVerticalGroup(
            internalAltaAlbumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(internalAltaAlbum);

        internalAltaPerfil.setClosable(true);
        internalAltaPerfil.setTitle("Alta Perfil");
        internalAltaPerfil.setToolTipText("");
        internalAltaPerfil.setPreferredSize(new java.awt.Dimension(1422, 800));
        try {
            internalAltaPerfil.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        internalAltaPerfil.setVisible(true);

        javax.swing.GroupLayout internalAltaPerfilLayout = new javax.swing.GroupLayout(internalAltaPerfil.getContentPane());
        internalAltaPerfil.getContentPane().setLayout(internalAltaPerfilLayout);
        internalAltaPerfilLayout.setHorizontalGroup(
            internalAltaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );
        internalAltaPerfilLayout.setVerticalGroup(
            internalAltaPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(internalAltaPerfil);
        try {
            internalAltaPerfil.setMaximum(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        SesionDropDown.setText("Sesion");

        cerrarOption.setText("Cerrar");
        cerrarOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarOptionActionPerformed(evt);
            }
        });
        SesionDropDown.add(cerrarOption);

        jMenuBar1.add(SesionDropDown);

        AltasDropDown.setText("Altas");

        AltaPerfil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        AltaPerfil.setText("Alta Perfil");
        AltaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaPerfilActionPerformed(evt);
            }
        });
        AltasDropDown.add(AltaPerfil);

        AltaAlbum.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        AltaAlbum.setText("Alta Album");
        AltaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltaAlbumActionPerformed(evt);
            }
        });
        AltasDropDown.add(AltaAlbum);

        jMenuBar1.add(AltasDropDown);

        ConsultasDropDown.setText("Consultas");
        jMenuBar1.add(ConsultasDropDown);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarOptionActionPerformed
        this.dispose();
    }//GEN-LAST:event_cerrarOptionActionPerformed

    private void AltaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaPerfilActionPerformed
        this.internalAltaPerfil.setVisible(true);
    }//GEN-LAST:event_AltaPerfilActionPerformed

    private void AltaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaAlbumActionPerformed
        this.internalAltaAlbum.setVisible(true);
    }//GEN-LAST:event_AltaAlbumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaAlbum;
    private javax.swing.JMenuItem AltaPerfil;
    private javax.swing.JMenu AltasDropDown;
    private javax.swing.JMenu ConsultasDropDown;
    private javax.swing.JMenu SesionDropDown;
    private javax.swing.JMenuItem cerrarOption;
    private javax.swing.JInternalFrame internalAltaAlbum;
    private javax.swing.JInternalFrame internalAltaPerfil;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
